[versions]
activity = "1.9.0"
compose = "1.7.0-beta03"
compose-constraintlayout = "1.0.1"
compose-material3 = "1.3.0-beta03"
compose-tv = "1.0.0-beta01"
compose-tv-foundation = "1.0.0-alpha10"
core = "1.13.1"
core-splashscreen = "1.0.1"
dataStore = "1.1.1"
lifecycle = "2.8.0"
media3 = "1.3.1"
room = "2.6.1"
webkit = "1.11.0"

[libraries]
# https://developer.android.com/jetpack/androidx/releases/activity
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

# https://developer.android.com/jetpack/compose/layout
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintlayout" }

# https://developer.android.com/jetpack/androidx/releases/tv
compose-tv-foundation = { module = "androidx.tv:tv-foundation", version.ref = "compose-tv-foundation" }
compose-tv-material = { module = "androidx.tv:tv-material", version.ref = "compose-tv" }

# https://developer.android.com/jetpack/androidx/releases/compose-ui
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }

# https://developer.android.com/jetpack/androidx/releases/ui
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

# https://developer.android.com/jetpack/androidx/releases/compose-material
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }

# https://developer.android.com/jetpack/androidx/releases/compose-material3
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose-material3" }

# https://developer.android.com/jetpack/androidx/releases/compose-runtime
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }

# https://developer.android.com/jetpack/androidx/releases/core
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }

# https://developer.android.com/topic/libraries/architecture/datastore
datastore-typed = { module = "androidx.datastore:datastore", version.ref = "dataStore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

# https://developer.android.com/jetpack/androidx/releases/lifecycle
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# https://developer.android.com/jetpack/androidx/releases/media3
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
media3-decoder = { module = "androidx.media3:media3-decoder", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }

# https://developer.android.com/jetpack/androidx/releases/room
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-testing = { module = "androidx.room:room-ktx", version.ref = "room" }

# https://developer.android.com/jetpack/androidx/releases/webkit
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }