[versions]
akdanmaku = "1.0.3"
androidsvg = "1.4"
coil = "2.6.0"
firebase-bom = "33.1.0"
geetest-sensebot = "4.4.2.1"
grpc = "1.63.0"
grpc-kotlin = "1.4.1"
jsoup = "1.17.2"
koin = "3.5.6"
koin-compose = "3.5.6"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization = "1.7.0"
ktor = "2.3.11"
ktor-jsoup = "2.3.0"
logging = "7.0.0"
lottie = "6.4.1"
material = "1.12.0"
protobuf = "4.26.1"
#noinspection GradleDependency 之后的版本要求 minSDK >= 23
qrcode = "3.3.0"
rememberPreference = "1.0.2"
slf4j-android-mvysny = "2.0.4"
slf4j-simple = "2.0.9"
vlc = "3.6.0-eap5"

[libraries]
# https://github.com/KwaiAppTeam/AkDanmaku
akdanmaku = { module = "com.kuaishou:akdanmaku", version.ref = "akdanmaku" }

# https://github.com/BigBadaboom/androidsvg
androidSvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }

# https://coil-kt.github.io/coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

# https://firebase.google.com/docs/android/setup
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }

# https://docs.geetest.com/sensebot/deploy/client/android
geetest-sensebot = { module = "com.geetest.sensebot:sensebot", version.ref = "geetest-sensebot" }

# https://github.com/grpc/grpc-kotlin
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
grpc-android = { module = "io.grpc:grpc-android", version.ref = "grpc" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }

# https://jsoup.org/
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

# https://insert-koin.io
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }

# https://kotlinlang.org/docs/jvm-test-using-junit.html
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# https://ktor.io/docs
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }

# https://github.com/T-Fowl/ktor-jsoup
ktor-jsoup = { module = "com.tfowl.ktor:ktor-jsoup", version.ref = "ktor-jsoup" }

# https://github.com/MicroUtils/kotlin-logging
logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }

# https://airbnb.io/lottie
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

# https://github.com/material-components/material-components-android
material = { module = "com.google.android.material:material", version.ref = "material" }

# https://github.com/g0dkar/qrcode-kotlin
qrcode = { module = "io.github.g0dkar:qrcode-kotlin-android", version.ref = "qrcode" }

# https://github.com/burnoo/compose-remember-preference
rememberPreference = { module = "dev.burnoo:compose-remember-preference", version.ref = "rememberPreference" }

# https://gitlab.com/mvysny/slf4j-handroid
slf4j-android-mvysny = { module = "com.gitlab.mvysny.slf4j:slf4j-handroid", version.ref = "slf4j-android-mvysny" }

# https://www.slf4j.org
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-simple" }

# https://code.videolan.org/videolan/vlc-android
vlc-android-all = { module = "org.videolan.android:libvlc-all", version.ref = "vlc" }
