name: Alpha Build Manually (Without sign)

on:
  workflow_dispatch:
    inputs:
      google_services_json:
        description: "google-services.json"
        required: true

jobs:
  build-alpha:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
          submodules: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Write google-services.json
        env:
          DATA: ${{ github.event.inputs.google_services_json }}
        run: echo $DATA > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build lite apk
        run: ./gradlew assembleLiteAlpha assembleLiteDebug

      - name: Build default apk
        run: ./gradlew assembleDefaultAlpha assembleDefaultDebug

      - name: Read lite alpha apk output metadata
        id: apk-meta-lite-alpha
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/lite/alpha/output-metadata.json

      - name: Read lite debug apk output metadata
        id: apk-meta-lite-debug
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/lite/debug/output-metadata.json

      - name: Read default alpha apk output metadata
        id: apk-meta-default-alpha
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/default/alpha/output-metadata.json

      - name: Read default debug apk output metadata
        id: apk-meta-default-debug
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/default/debug/output-metadata.json

      - name: Parse lite apks info
        id: lite-info
        run: |
          echo "lite_alpha_info_apk_filename=${{ fromJson(steps.apk-meta-lite-alpha.outputs.content).elements[0].outputFile }}" >> $GITHUB_ENV
          echo "lite_debug_info_apk_filename=${{ fromJson(steps.apk-meta-lite-debug.outputs.content).elements[0].outputFile }}" >> $GITHUB_ENV

      - name: Parse default apks info
        id: default-info
        run: |
          echo "default_alpha_info_version_code=${{ fromJson(steps.apk-meta-default-alpha.outputs.content).elements[0].versionCode }}" >> $GITHUB_ENV
          echo "default_alpha_info_version_name=${{ fromJson(steps.apk-meta-default-alpha.outputs.content).elements[0].versionName }}" >> $GITHUB_ENV
          echo "default_debug_info_version_code=${{ fromJson(steps.apk-meta-default-debug.outputs.content).elements[0].versionCode }}" >> $GITHUB_ENV
          echo "default_debug_info_version_name=${{ fromJson(steps.apk-meta-default-debug.outputs.content).elements[0].versionName }}" >> $GITHUB_ENV

      # upload artifacts lite-debug

      - name: Archive lite debug build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Lite debug build artifact
          path: app/build/outputs/apk/lite/debug/${{ env.lite_debug_info_apk_filename }}

      # upload artifacts lite-alpha

      - name: Archive lite alpha build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Lite alpha build artifact
          path: app/build/outputs/apk/lite/alpha/${{ env.lite_alpha_info_apk_filename }}

      - name: Archive lite alpha build mappings
        uses: actions/upload-artifact@v3
        with:
          name: Lite alpha build mappings
          path: app/build/outputs/mapping/liteAlpha

      # upload artifacts default-debug

      - name: Archive default debug build artifacts (universal)
        uses: actions/upload-artifact@v3
        with:
          name: Default debug build artifact (universal)
          path: app/build/outputs/apk/default/debug/BV_${{ env.default_debug_info_version_code }}_${{ env.default_debug_info_version_name }}_default_universal.apk

      - name: Archive default debug build artifacts (armeabi-v7a)
        uses: actions/upload-artifact@v3
        with:
          name: Default debug build artifact (armeabi-v7a)
          path: app/build/outputs/apk/default/debug/BV_${{ env.default_debug_info_version_code }}_${{ env.default_debug_info_version_name }}_default_armeabi-v7a.apk

      - name: Archive default debug build artifacts (arm64-v8a)
        uses: actions/upload-artifact@v3
        with:
          name: Default debug build artifact (arm64-v8a)
          path: app/build/outputs/apk/default/debug/BV_${{ env.default_debug_info_version_code }}_${{ env.default_debug_info_version_name }}_default_arm64-v8a.apk

      - name: Archive default debug build artifacts (x86)
        uses: actions/upload-artifact@v3
        with:
          name: Default debug build artifact (x86)
          path: app/build/outputs/apk/default/debug/BV_${{ env.default_debug_info_version_code }}_${{ env.default_debug_info_version_name }}_default_x86.apk

      - name: Archive default debug build artifacts (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: Default debug build artifact (x86_64)
          path: app/build/outputs/apk/default/debug/BV_${{ env.default_debug_info_version_code }}_${{ env.default_debug_info_version_name }}_default_x86_64.apk

      # upload artifacts default-alpha

      - name: Archive default alpha build mappings
        uses: actions/upload-artifact@v3
        with:
          name: Default alpha build mappings
          path: app/build/outputs/mapping/defaultAlpha

      - name: Archive default alpha build artifacts (universal)
        uses: actions/upload-artifact@v3
        with:
          name: Default alpha build artifact (universal)
          path: app/build/outputs/apk/default/alpha/BV_${{ env.default_alpha_info_version_code }}_${{ env.default_alpha_info_version_name }}_default_universal.apk

      - name: Archive default alpha build artifacts (armeabi-v7a)
        uses: actions/upload-artifact@v3
        with:
          name: Default alpha build artifact (armeabi-v7a)
          path: app/build/outputs/apk/default/alpha/BV_${{ env.default_alpha_info_version_code }}_${{ env.default_alpha_info_version_name }}_default_armeabi-v7a.apk

      - name: Archive default alpha build artifacts (arm64-v8a)
        uses: actions/upload-artifact@v3
        with:
          name: Default alpha build artifact (arm64-v8a)
          path: app/build/outputs/apk/default/alpha/BV_${{ env.default_alpha_info_version_code }}_${{ env.default_alpha_info_version_name }}_default_arm64-v8a.apk

      - name: Archive default alpha build artifacts (x86)
        uses: actions/upload-artifact@v3
        with:
          name: Default alpha build artifact (x86)
          path: app/build/outputs/apk/default/alpha/BV_${{ env.default_alpha_info_version_code }}_${{ env.default_alpha_info_version_name }}_default_x86.apk

      - name: Archive default alpha build artifacts (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: Default alpha build artifact (x86_64)
          path: app/build/outputs/apk/default/alpha/BV_${{ env.default_alpha_info_version_code }}_${{ env.default_alpha_info_version_name }}_default_x86_64.apk
