name: Release Build

on:
  push:
    branches:
      - master

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Write google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add signing properties
        env:
          SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}
        run: |
          echo ${{ secrets.SIGNING_PROPERTIES }} > encoded_signing_properties
          base64 -d encoded_signing_properties > signing.properties

      - name: Add jks file
        run: |
          echo ${{ secrets.SIGN_KEY }} > ./encoded_key
          base64 -d encoded_key > key.jks

      - name: Build apk
        run: ./gradlew assembleRelease assembleDebug

      - name: Read release apk output metadata
        id: apk-meta-release
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/release/output-metadata.json

      - name: Read debug apk output metadata
        id: apk-meta-debug
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/debug/output-metadata.json

      - name: Parse release info
        id: release-info
        run: |
          echo "release_info_version_code=${{ fromJson(steps.apk-meta-release.outputs.content).elements[0].versionCode }}" >> $GITHUB_ENV
          echo "release_info_version_name=${{ fromJson(steps.apk-meta-release.outputs.content).elements[0].versionName }}" >> $GITHUB_ENV
          echo "release_info_apk_filename=${{ fromJson(steps.apk-meta-release.outputs.content).elements[0].outputFile }}" >> $GITHUB_ENV

      - name: Parse debug info
        id: debug-info
        run: |
          echo "debug_info_version_code=${{ fromJson(steps.apk-meta-debug.outputs.content).elements[0].versionCode }}" >> $GITHUB_ENV
          echo "debug_info_version_name=${{ fromJson(steps.apk-meta-debug.outputs.content).elements[0].versionName }}" >> $GITHUB_ENV
          echo "debug_info_apk_filename=${{ fromJson(steps.apk-meta-debug.outputs.content).elements[0].outputFile }}" >> $GITHUB_ENV

      - name: Get current time
        id: date
        run: echo "current_time=$(date +'%Y-%m-%d_%H:%M:%S')" >> $GITHUB_ENV

      - name: Zip release outputs
        uses: vimtor/action-zip@v1.1
        with:
          files: app/build/outputs
          dest: BV_${{ env.release_info_version_code }}_${{ env.release_info_version_name }}_${{ env.current_time }}.zip

      - name: Upload release outputs
        uses: Difegue/action-megacmd@1.2.0
        with:
          args: put BV_${{ env.release_info_version_code }}_${{ env.release_info_version_name }}_${{ env.current_time }}.zip
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}

      - name: Upload release apk to app center
        uses: wzieba/AppCenter-Github-Action@v1.3.3
        with:
          appName: aaa1115910-gmail.com/BV
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Public
          file: app/build/outputs/apk/release/${{ env.release_info_apk_filename }}
          notifyTesters: true
          debug: false

      - name: Archive release build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release build artifact
          path: app/build/outputs/apk/release/${{ env.release_info_apk_filename }}

      - name: Archive release build mappings
        uses: actions/upload-artifact@v3
        with:
          name: Release build mappings
          path: app/build/outputs/mapping/release

      - name: Archive debug build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Debug build artifact
          path: app/build/outputs/apk/debug/${{ env.debug_info_apk_filename }}
